[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NETLIFY_FEEDBACK_DISABLED = "true"

[context.production.environment]
  NETLIFY_FEEDBACK_DISABLED = "true"

[context.deploy-preview.environment]
  NETLIFY_FEEDBACK_DISABLED = "true"

[context.branch-deploy.environment]
  NETLIFY_FEEDBACK_DISABLED = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
